In [1]:
'''import sys
sys.path.insert(0, 'nice')
'''
#os.environ['OMP_NUM_THREADS'] = '24'

import numpy as np
import ase.io as ase_io
from ase import Atoms
import tqdm
import time
import copy
from sklearn.linear_model import BayesianRidge

import nice
from nice.blocks import *
from nice.unrolling_individual_pca import UnrollingIndividualPCA

from matplotlib import pyplot as plt


In [2]:
a = np.random.rand(100, 50, 11)

In [3]:
pca = UnrollingIndividualPCA(n_components = 30, random_state = 0)

In [4]:
pca.fit(a, 50, 5)

In [5]:
b1 = pca.transform(a, 50, 5, method = 'serial')
print(b1.shape)

(100, 30, 11)


In [6]:
b2 = pca.transform(a, 50, 5, method = 'parallel')
print(b2.shape)

(100, 30, 11)


In [7]:
print(b1[0:3, 0:3, 0:3])


[[[ 3.44272636e+00  3.31322184e+00  3.82826946e+00]
  [-1.36836857e-01  6.11519794e-01 -7.05117776e-01]
  [-3.22424771e-01 -1.45226017e-03  5.57996801e-02]]

 [[ 3.33531980e+00  3.68597352e+00  3.15352950e+00]
  [ 1.84450121e-01 -5.36372801e-01 -7.51219714e-01]
  [ 4.83694429e-01 -1.11344982e-01 -4.87227842e-01]]

 [[ 3.91558330e+00  3.63739334e+00  3.35873110e+00]
  [ 2.74298661e-02 -6.14011123e-01 -2.97356058e-01]
  [-1.01254015e-01  5.12425037e-01  6.81570726e-01]]]


In [8]:
print(b2[0:3, 0:3, 0:3])

[[[ 3.44272636e+00  3.31322184e+00  3.82826946e+00]
  [-1.36836857e-01  6.11519794e-01 -7.05117776e-01]
  [-3.22424771e-01 -1.45226017e-03  5.57996801e-02]]

 [[ 3.33531980e+00  3.68597352e+00  3.15352950e+00]
  [ 1.84450121e-01 -5.36372801e-01 -7.51219714e-01]
  [ 4.83694429e-01 -1.11344982e-01 -4.87227842e-01]]

 [[ 3.91558330e+00  3.63739334e+00  3.35873110e+00]
  [ 2.74298661e-02 -6.14011123e-01 -2.97356058e-01]
  [-1.01254015e-01  5.12425037e-01  6.81570726e-01]]]


In [9]:
pca = UnrollingIndividualPCA(n_components = 30, random_state = 0)
pca.fit(a, 50, 5)
b1 = pca.transform(a, 50, 5)

pca = UnrollingIndividualPCA(n_components = 30, random_state = 0)
b2 = pca.fit_transform(a, 50, 5)
print(np.sum(np.abs(b1 - b2)))

2.3910765860633626e-12


In [10]:
print(pca.importances_[0:10])

[0.82160374 0.00774548 0.00746329 0.00737247 0.00719865 0.00714609
 0.00695957 0.00683902 0.00674993 0.00664486]


In [11]:
pca2 = UnrollingIndividualPCA(n_components = 30, random_state = 0, normalize_importances = False)
b2 = pca2.fit_transform(a, 50, 5)
print(pca2.importances_[0:10])

[12.69656682  0.11969402  0.11533321  0.11392963  0.11124352  0.11043136
  0.10754903  0.10568615  0.10430938  0.10268563]


In [13]:
print(pca.importances_ / pca2.importances_)

[0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107
 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107
 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107
 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107 0.0647107
 0.0647107 0.0647107]
