In [1]:
!rm -r build
!python3 setup.py build_ext --inplace

running build_ext
building 'nice.naive' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/nice
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c nice/naive.c -o build/temp.linux-x86_64-3.6/nice/naive.o -O3 -fopenmp
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/nice
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/nice/naive.o -o build/lib.linux-x86_64-3.6/nice/naive.cpython-36m-x86_64-linux-gnu.so -fopenmp
building 'nice.nice_utilities' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-secur

copying build/lib.linux-x86_64-3.6/nice/rascal_coefficients.cpython-36m-x86_64-linux-gnu.so -> nice
copying build/lib.linux-x86_64-3.6/nice/spherical_coefficients.cpython-36m-x86_64-linux-gnu.so -> nice
copying build/lib.linux-x86_64-3.6/nice/spherical_harmonics.cpython-36m-x86_64-linux-gnu.so -> nice
copying build/lib.linux-x86_64-3.6/nice/test_parallel.cpython-36m-x86_64-linux-gnu.so -> nice
copying build/lib.linux-x86_64-3.6/nice/thresholding.cpython-36m-x86_64-linux-gnu.so -> nice
copying build/lib.linux-x86_64-3.6/nice/unrolling_individual_pca.cpython-36m-x86_64-linux-gnu.so -> nice
copying build/lib.linux-x86_64-3.6/nice/unrolling_pca.cpython-36m-x86_64-linux-gnu.so -> nice


In [2]:
import numpy as np
import time
from nice.transformers import *
from nice.nice_utilities import Data

In [3]:
blocks = [np.random.rand(100, 20) for _ in range(3)]
new_one = np.random.rand(100, 30)

In [4]:
clf = InvariantsPurifier()
clf.fit(blocks, new_one)

In [5]:
res = clf.transform(blocks, new_one)
print(res.shape)

(100, 30)


In [6]:
blocks = [np.random.rand(100, 20, 9) for _ in range(4)]
new_one = np.random.rand(100, 25, 11)

In [7]:
clf = CovariantsIndividualPurifier()
clf.fit(blocks, new_one, 2)

In [8]:
result = clf.transform(blocks, new_one, 2)
print(result.shape)

(100, 25, 5)


In [9]:
old_datas = [Data(np.random.rand(100, 10, 4, 7), np.array([10] * 4)) for _ in range(5)]
new_data = Data(np.random.rand(100, 9, 4, 7), np.array([9] * 4))

In [10]:
clf = CovariantsPurifier(3)
clf.fit(old_datas, new_data)

In [11]:
result = clf.transform(old_datas, new_data)

In [12]:
print(result.covariants_.shape)
print(result.actual_sizes_)

(100, 9, 4, 7)
[9 9 9 9]


In [13]:
old_datas_even = [Data(np.random.rand(100, 10, 4, 7), np.array([10] * 4)) for _ in range(5)]
new_data_even = Data(np.random.rand(100, 9, 4, 7), np.array([9] * 4))

old_datas_odd = [Data(np.random.rand(100, 10, 4, 7), np.array([10] * 4)) for _ in range(5)]
new_data_odd = Data(np.random.rand(100, 9, 4, 7), np.array([9] * 4))

clf = CovariantsPurifierBoth(3)
clf.fit(old_datas_even, new_data_even, old_datas_odd, new_data_odd)


In [14]:
data_even, data_odd = clf.transform(old_datas_even, new_data_even, old_datas_odd, new_data_odd)

In [15]:
print(data_even.covariants_.shape)
print(data_even.actual_sizes_)

print(data_odd.covariants_.shape)
print(data_odd.actual_sizes_)

(100, 9, 4, 7)
[9 9 9 9]
(100, 9, 4, 7)
[9 9 9 9]
